# Generated by Django 5.1.1 on 2024-11-08 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_call_app', '0002_alter_bill_capital_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='investment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
